---
- name: Install etcd for etcdctl
  package: name=etcd state=present
  when: not openshift.common.is_atomic | bool

- name: Configure etcd profile.d alises
  copy:
    src: etcdctl.sh
    dest: /etc/profile.d/etcdctl.sh
    mode: 0755
    owner: root
    group: root
